name: GA
on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Run
        run: |
          ${{ secrets.COMMAND }}
