name: GA
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
